#!/bin/sh
set -eu
REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
. "$REPO_ROOT/lib/common.sh"

usage() {
  cat <<'USAGE'
Usage: install.sh <profile> [options]

Install a profile from this repository into its own Claude Code config root,
leaving ~/.claude untouched.

Options:
  --mode symlink|copy   symlink (default) keeps the repo as source of truth;
                        copy takes a frozen snapshot
  --target DIR          override the target from profile.json
  --shim-dir DIR        where to write the launch shim (default ~/.local/bin)
  --dry-run             print every action, change nothing
  -h, --help            show this help

Profiles: see profiles/ in this repository.
USAGE
}

PROFILE=""
MODE="symlink"
TARGET_OVERRIDE=""
SHIM_DIR="$HOME/.local/bin"
DRY_RUN=0

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --mode) MODE="${2:-}"; shift 2 ;;
    --target) TARGET_OVERRIDE="${2:-}"; shift 2 ;;
    --shim-dir) SHIM_DIR="${2:-}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -*) die "unknown option: $1" ;;
    *) [ -z "$PROFILE" ] || die "only one profile at a time"; PROFILE="$1"; shift ;;
  esac
done
export DRY_RUN

[ -n "$PROFILE" ] || { usage; die "no profile given"; }
case "$MODE" in symlink|copy) ;; *) die "unknown mode: $MODE" ;; esac

PROFILE_DIR="$REPO_ROOT/profiles/$PROFILE"
[ -d "$PROFILE_DIR" ] || die "unknown profile: $PROFILE"
[ -f "$PROFILE_DIR/profile.json" ] || die "profile has no profile.json: $PROFILE"

if [ -n "$TARGET_OVERRIDE" ]; then
  TARGET="$(expand_path "$TARGET_OVERRIDE")"
else
  TARGET="$(expand_path "$(json_field "$PROFILE_DIR/profile.json" target)")"
fi
SHIM_NAME="$(json_field "$PROFILE_DIR/profile.json" shim)"
[ -n "$SHIM_NAME" ] || die "profile.json has no shim name"

guard_target "$TARGET" "$REPO_ROOT"

log "profile:  $PROFILE"
log "target:   $TARGET"
log "mode:     $MODE"
log "shim:     $SHIM_DIR/$SHIM_NAME"
if [ "$DRY_RUN" = "1" ]; then log "(dry run — nothing will change)"; fi

run mkdir -p "$TARGET"

MANIFEST="$TARGET/.omega-ai-manifest"
[ "$DRY_RUN" = "1" ] || : > "$MANIFEST"

# Content directories: shared first, profile second so the profile wins.
for dir in agents skills commands hooks memory; do
  for installed in $(install_entries "$REPO_ROOT/shared/$dir" "$TARGET/$dir" "$MODE"); do
    manifest_add "$MANIFEST" "$installed"
  done
  for installed in $(install_entries "$PROFILE_DIR/$dir" "$TARGET/$dir" "$MODE"); do
    manifest_add "$MANIFEST" "$installed"
  done
done

# CLAUDE.md is generated, so it is always written as a real file.
if [ "$DRY_RUN" = "1" ]; then
  log "DRY  render $TARGET/CLAUDE.md"
else
  {
    printf '<!-- GENERATED by omega-ai install.sh from shared/CLAUDE.part.md\n'
    printf '     and profiles/%s/CLAUDE.md. Edits here are overwritten. -->\n\n' "$PROFILE"
    if [ -f "$REPO_ROOT/shared/CLAUDE.part.md" ]; then
      cat "$REPO_ROOT/shared/CLAUDE.part.md"
    fi
    printf '\n'
    cat "$PROFILE_DIR/CLAUDE.md"
  } > "$TARGET/CLAUDE.md"
  manifest_add "$MANIFEST" "$TARGET/CLAUDE.md"
fi

# settings.json is copied, never linked: Claude Code writes to it in-session.
if [ "$DRY_RUN" = "1" ]; then
  log "DRY  copy $TARGET/settings.json"
elif [ -f "$PROFILE_DIR/settings.json" ]; then
  if [ -f "$TARGET/settings.json" ] && ! cmp -s "$PROFILE_DIR/settings.json" "$TARGET/settings.json"; then
    backup="$TARGET/settings.json.bak-$(date +%Y%m%d%H%M%S)"
    cp "$TARGET/settings.json" "$backup"
    warn "existing settings.json differed; backed up to $backup"
  fi
  cp "$PROFILE_DIR/settings.json" "$TARGET/settings.json"
  manifest_add "$MANIFEST" "$TARGET/settings.json"
fi

if [ "$DRY_RUN" = "1" ]; then
  log "DRY  write shim $SHIM_DIR/$SHIM_NAME"
else
  mkdir -p "$SHIM_DIR"
  cat > "$SHIM_DIR/$SHIM_NAME" <<SHIM
#!/usr/bin/env sh
# Generated by omega-ai install.sh — launches Claude Code against the
# $PROFILE profile's isolated config root.
CLAUDE_CONFIG_DIR="$TARGET" exec claude "\$@"
SHIM
  chmod +x "$SHIM_DIR/$SHIM_NAME"
  manifest_add "$MANIFEST" "$SHIM_DIR/$SHIM_NAME"

  case ":$PATH:" in
    *":$SHIM_DIR:"*) ;;
    *) warn "$SHIM_DIR is not on your PATH. Add it:
    export PATH=\"$SHIM_DIR:\$PATH\"" ;;
  esac
fi

log ""
log "Installed. Launch with: $SHIM_NAME"

if [ "$DRY_RUN" = "1" ]; then
  log "(dry run complete)"
else
  log ""
  sh "$REPO_ROOT/doctor.sh" "$PROFILE" --target "$TARGET"
fi
